=== UW-Madison-DoIT/mumstatus/src/main/resources/xsd/serverConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2012, Board of Regents of the University of
    Wisconsin System. See the NOTICE file distributed with
    this work for additional information regarding copyright
    ownership. Board of Regents of the University of Wisconsin
    System licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="checkUrl" type="xs:string"/>
                <xs:element maxOccurs="unbounded" name="server-group" type="server-group_type"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="server-group_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element maxOccurs="unbounded" name="server" type="server_type"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="l4-link" type="name-link_type"/>
            <xs:element maxOccurs="unbounded" name="port-info" type="port-info_type"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="server_type">
        <xs:sequence>
            <xs:element name="service" type="xs:string" minOccurs="0"/>
            <xs:element name="server" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="name-link_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element minOccurs="0" name="link" type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="port-info_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element maxOccurs="unbounded" name="port">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:int">
                            <xs:attribute name="secure" type="xs:boolean" default="false"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== UW-Madison-DoIT/mumstatus/src/main/resources/serverConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2012, Board of Regents of the University of
    Wisconsin System. See the NOTICE file distributed with
    this work for additional information regarding copyright
    ownership. Board of Regents of the University of Wisconsin
    System licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="xsd/serverConfig.xsd">
    <checkUrl>/misc/l4status.html</checkUrl>
    <server-group>
        <name>Madison VIPs</name>
        <server>
            <service>my.wisc.edu</service>
            <server>my.wisc.edu</server>
        </server>
        <server>
            <service>my-qa.wisc.edu</service>
            <server>my-qa.wisc.edu</server>
        </server>
        <port-info>
            <name>Madison</name>
            <port>80</port>
            <port secure="true">443</port>
        </port-info>
    </server-group>
    <server-group>
        <name>System VIPs</name>
        <server>
            <service>my.wisconsin.edu</service>
            <server>my.wisconsin.edu</server>
        </server>
        <server>
            <service>my-qa.wisconsin.edu</service>
            <server>my-qa.wisconsin.edu</server>
        </server>
        <port-info>
            <name>System</name>
            <port>80</port>
            <port secure="true">443</port>
        </port-info>
    </server-group>
    <server-group>
        <name>PROD</name>
        <server>
            <service>mumapp12.doit.wisc.edu</service>
            <server>unas.doit.wisc.edu</server>
        </server>
        <server>
            <service>mumapp13.doit.wisc.edu</service>
            <server>amenhotep.doit.wisc.edu</server>
        </server>
        <server>
            <service>mumapp14.doit.wisc.edu</service>
            <server>nefertiti.doit.wisc.edu</server>
        </server>
        <server>
            <service>mumapp15.doit.wisc.edu</service>
            <server>amun.doit.wisc.edu</server>
        </server>
        <server>
            <service>mumapp16.doit.wisc.edu</service>
            <server>anubis.doit.wisc.edu</server>
        </server>
        <l4-link>
            <name>Madison-80</name>
            <link>https://stats.net.wisc.edu/layer4/10.128.9.72.MY-144.92.197.135-TCP80.html</link>
        </l4-link>
        <l4-link>
            <name>Madison-443</name>
            <link>https://stats.net.wisc.edu/layer4/10.128.9.72.MY-144.92.197.135-TCP443.html</link>
        </l4-link>
        <l4-link>
            <name>System-80</name>
            <link>https://stats.net.wisc.edu/layer4/10.128.9.72.MY-144.92.197.157-TCP80.html</link>
        </l4-link>
        <l4-link>
            <name>System-443</name>
            <link>https://stats.net.wisc.edu/layer4/10.128.9.72.MY-144.92.197.157-TCP443.html</link>
        </l4-link>
        <port-info>
            <name>Madison</name>
            <port>80</port>
            <port secure="true">443</port>
        </port-info>
        <port-info>
            <name>System</name>
            <port>8080</port>
            <port secure="true">8443</port>
        </port-info>
    </server-group>
    <server-group>
        <name>QA</name>
        <server>
            <service>tmumapp8.doit.wisc.edu</service>
            <server>teti.doit.wisc.edu</server>
        </server>
        <server>
            <service>tmumapp9.doit.wisc.edu</service>
            <server>ramesses.doit.wisc.edu</server>
        </server>
        <l4-link>
            <name>Old-80</name>
            <link>https://stats.net.wisc.edu/layer4/10.128.9.37.MY-144.92.170.7-TCP80.html</link>
        </l4-link>
        <l4-link>
            <name>Old-443</name>
            <link>https://stats.net.wisc.edu/layer4/10.128.9.37.MY-144.92.170.7-TCP443.html</link>
        </l4-link>
        <port-info>
            <name>Madison</name>
            <port>80</port>
            <port secure="true">443</port>
        </port-info>
        <port-info>
            <name>System</name>
            <port>80</port>
            <port secure="true">443</port>
        </port-info>
    </server-group>
</config>
